# src/app.py

import gradio as gr
from utils import summarize_text # Import our summarization function

# Define the main interface function for Gradio
def interface(article_text):
    """
    The function that Gradio will call. It takes the user's input
    and returns the model's output.
    """
    summary = summarize_text(article_text)
    return summary

# Create the Gradio web interface
if __name__ == "__main__":
    # gr.Interface is the core class for building UIs
    app_interface = gr.Interface(
        fn=interface,  # The function to wrap
        inputs=gr.Textbox(lines=15, placeholder="Paste your article or text here..."), # Input component
        outputs=gr.Textbox(lines=5, label="Summary"), # Output component
        title="Project Synapse: An Adaptive Summarizer",
        description="Enter a piece of text and see the summary generated by the fine-tuned T5 model. This is the first step towards a model that learns from your feedback."
    )

    # Launch the web server
    print("Launching Gradio app...")
    app_interface.launch()